# nse500_list.py

nse_500 = [
    "RELIANCE", "TCS", "INFY", "HDFCBANK", "ICICIBANK",
    "BHARTIARTL", "SBIN", "HINDUNILVR", "ITC", "KOTAKBANK",
    "LT", "AXISBANK", "BAJFINANCE", "MARUTI", "ASIANPAINT",
    "WIPRO", "TITAN", "SUNPHARMA", "ULTRACEMCO", "ADANIENT",
    "ADANIGREEN", "NTPC", "ONGC", "POWERGRID", "JSWSTEEL",
    "TATAMOTORS", "TATASTEEL", "EICHERMOT", "HDFCLIFE", "BPCL",
    "BAJAJ-AUTO", "UPL", "TECHM", "HCLTECH", "BRITANNIA",
    "GRASIM", "INDUSINDBK", "COALINDIA", "DIVISLAB", "DRREDDY",
    "HEROMOTOCO", "CIPLA", "NESTLEIND", "SHREECEM", "APOLLOHOSP"
]
